### PR TITLE
Implement test environment for Windows too

### PR DESCRIPTION
**Pull request by TBuc**
Only tested on Win10 x64.

### CODE REVIEW

**Comment by daveyarwood** [comment]
Hey, thanks for the PR! The code looks good to me, and the tests are still passing for me on Ubuntu, so that's good. I assume the tests pass on your Windows system? If so, I'll take that as a "good enough" sign that your implementation of `getProcesses` works correctly :)

It does look like this branch is a bit behind master -- could you merge (or rebase on top of) master and resolve any merge conflicts?

**Comment by TBuc** [comment]
So 8 months and various JDK releases (1.8.181, 1.8.191, 1.8.211) have passed, but this didn't work and yet doesn't work on my Windows OS.
All of a sudden, it stopped working and never got back.

_boot dev_ works fine, but when trying to run _boot test_ I get the following error:
> C:\Users\LocalAdmin\IdeaProjects\alda-client-java>boot test
> Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
> Compiling 49 Java source files...
>                                        java.lang.Thread.run                  Thread.java:  748
>          java.util.concurrent.ThreadPoolExecutor$Worker.run      ThreadPoolExecutor.java:  624
>           java.util.concurrent.ThreadPoolExecutor.runWorker      ThreadPoolExecutor.java: 1149
>                         java.util.concurrent.FutureTask.run              FutureTask.java:  266
>                                                         ...
>                         clojure.core/binding-conveyor-fn/fn                     core.clj: 1938
>                                           boot.core/boot/fn                     core.clj: 1032
>                                         boot.core/run-tasks                     core.clj: 1022
>                              boot.task.built-in/fn/fn/fn/fn                 built_in.clj:  815
>                   radicalzephyr.boot-junit/eval282/fn/fn/fn               boot_junit.clj:   50
>                radicalzephyr.boot-junit/eval282/fn/fn/fn/fn               boot_junit.clj:   51
>                                           boot.pod/eval-in*                      pod.clj:  471
>                                                         ...
> org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:  102
> org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:  109
>                                                         ...
>                                           boot.pod/eval-in*                      pod.clj:  468
>                                           clojure.core/eval                     core.clj: 3105
>                                                         ...
>                                          pod$eval525.invoke                NO_SOURCE_FILE
>                                    pod$eval525.invokeStatic                NO_SOURCE_FILE
>                                                         ...
>                           cljunit.core/run-tests-in-classes                     core.clj:  104
>                           cljunit.core/run-tests-in-classes                     core.clj:  112
>                                            clojure.core/seq                     core.clj:  137
>                                                         ...
>                                      clojure.core/filter/fn                     core.clj: 2700
>                                            clojure.core/seq                     core.clj:  137
>                                                         ...
>                                         clojure.core/map/fn                     core.clj: 2646
>                        cljunit.core/run-tests-in-classes/fn                     core.clj:  110
>                             java.lang.ClassLoader.loadClass             ClassLoader.java:  357
>                                                         ...
>                             java.lang.ClassLoader.loadClass             ClassLoader.java:  411
>                                                         ...
>                             java.lang.ClassLoader.loadClass             ClassLoader.java:  411
>                                                         ...
>                             java.lang.ClassLoader.loadClass             ClassLoader.java:  411
>                             java.lang.ClassLoader.loadClass             ClassLoader.java:  424
>                           java.net.URLClassLoader.findClass          URLClassLoader.java:  362
>                 java.security.AccessController.doPrivileged         AccessController.java
>                               java.net.URLClassLoader$1.run          URLClassLoader.java:  363
>                               java.net.URLClassLoader$1.run          URLClassLoader.java:  369
>                          java.net.URLClassLoader.access$100          URLClassLoader.java:   74
>                         java.net.URLClassLoader.defineClass          URLClassLoader.java:  468
>                 java.security.SecureClassLoader.defineClass       SecureClassLoader.java:  142
>                           java.lang.ClassLoader.defineClass             ClassLoader.java:  763
>                          java.lang.ClassLoader.defineClass1              ClassLoader.java
> java.lang.NoClassDefFoundError: \alda\testutils\TestEnvironment (wrong name: alda/testutils/TestEnvironment)
>     clojure.lang.ExceptionInfo: \alda\testutils\TestEnvironment (wrong name: alda/testutils/TestEnvironment)
>     line: 101

I've also tried with OpenJDK 12 but nothing changes.
Upgrading adzerk/bootlaces to 0.2.0 won't help.

Any ideas?

**Comment by TBuc** [comment]
Please note I've taken [this bug](https://github.com/boot-clj/boot/issues/639) as a reference, but couldn't identify a suitable fix for my case.

**Comment by daveyarwood** [comment]
Hmm... off-hand, I'm not exactly sure what would be causing that to happen. I did notice that we don't have a `boot.properties` file in this repo, which means it will use whatever version of Boot you have installed. Could you post the output of `boot -V`?

A couple people who posted in that issue mentioned that it was fixed by upgrading to Boot 2.7.2, and at this point 2.8.3 is the latest. I would try upgrading to the latest Boot by running `boot -u`. After pasting the output of `boot -V` here, of course :)

Another thing to note: I don't think we can support building Alda with newer versions of Java yet, so I would continue to use JDK 8.

**Comment by TBuc** [comment]
Ehy thanks for the always prompt feedback!

Java version:
```
C:\Users\LocalAdmin>java -version
Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
```

I had just upgraded boot 2 days ago trying to fix the issue:
> C:\Users\LocalAdmin>boot -V
> Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
> #http://boot-clj.com
> #Wed Jun 26 22:18:24 CEST 2019
> BOOT_CLOJURE_NAME=org.clojure/clojure
> BOOT_CLOJURE_VERSION=1.8.0
> BOOT_VERSION=2.8.2
Unfortunately I don't recall which version I was running before that.

After upgrading to 2.8.2, _boot dev_ started working fine, while _boot test_ still fails.

I've just upgraded boot to 2.8.3, the error is the same but for a different \alda\repl\command source class every time I invoke _boot test_, most probably it's just about the order the source files get processed:
```
C:\Users\LocalAdmin\IdeaProjects\alda-client-java>boot test
Picked up JAVA_TOOL_OPTIONS:  -Dfile.encoding=UTF8
Compiling 49 Java source files...
                                       java.lang.Thread.run                  Thread.java:  748
         java.util.concurrent.ThreadPoolExecutor$Worker.run      ThreadPoolExecutor.java:  624
          java.util.concurrent.ThreadPoolExecutor.runWorker      ThreadPoolExecutor.java: 1149
                        java.util.concurrent.FutureTask.run              FutureTask.java:  266
                                                        ...
                        clojure.core/binding-conveyor-fn/fn                     core.clj: 1938
                                          boot.core/boot/fn                     core.clj: 1031
                                        boot.core/run-tasks                     core.clj: 1022
                       boot.task.built-in/eval2600/fn/fn/fn                 built_in.clj:  815
                 radicalzephyr.boot-junit/eval3261/fn/fn/fn               boot_junit.clj:   50
              radicalzephyr.boot-junit/eval3261/fn/fn/fn/fn               boot_junit.clj:   51
                                          boot.pod/eval-in*                      pod.clj:  471
                                                        ...
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:   97
org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.invoke  ClojureRuntimeShimImpl.java:  104
                                                        ...
                                          boot.pod/eval-in*                      pod.clj:  468
                                          clojure.core/eval                     core.clj: 3105
                                                        ...
                                         pod$eval525.invoke                NO_SOURCE_FILE
                                   pod$eval525.invokeStatic                NO_SOURCE_FILE
                                                        ...
                          cljunit.core/run-tests-in-classes                     core.clj:  104
                          cljunit.core/run-tests-in-classes                     core.clj:  112
                                           clojure.core/seq                     core.clj:  137
                                                        ...
                                     clojure.core/filter/fn                     core.clj: 2700
                                           clojure.core/seq                     core.clj:  137
                                                        ...
                                        clojure.core/map/fn                     core.clj: 2646
                       cljunit.core/run-tests-in-classes/fn                     core.clj:  110
                            java.lang.ClassLoader.loadClass             ClassLoader.java:  357
                                                        ...
                            java.lang.ClassLoader.loadClass             ClassLoader.java:  411
                                                        ...
                            java.lang.ClassLoader.loadClass             ClassLoader.java:  411
                                                        ...
                            java.lang.ClassLoader.loadClass             ClassLoader.java:  411
                            java.lang.ClassLoader.loadClass             ClassLoader.java:  424
                          java.net.URLClassLoader.findClass          URLClassLoader.java:  362
                java.security.AccessController.doPrivileged         AccessController.java
                              java.net.URLClassLoader$1.run          URLClassLoader.java:  363
                              java.net.URLClassLoader$1.run          URLClassLoader.java:  369
                         java.net.URLClassLoader.access$100          URLClassLoader.java:   74
                        java.net.URLClassLoader.defineClass          URLClassLoader.java:  468
                java.security.SecureClassLoader.defineClass       SecureClassLoader.java:  142
                          java.lang.ClassLoader.defineClass             ClassLoader.java:  763
                         java.lang.ClassLoader.defineClass1              ClassLoader.java
java.lang.NoClassDefFoundError: \alda\repl\commands\ReplNew (wrong name: alda/repl/commands/ReplNew)
    clojure.lang.ExceptionInfo: \alda\repl\commands\ReplNew (wrong name: alda/repl/commands/ReplNew)
    line: 101
```

Any idea is welcome.

**Comment by daveyarwood** [comment]
OK, so looking at the stacktrace more closely, it looks like the problem has something to do with the boot-junit task. I think the boot-junit task is turning the class names into paths and doing it in a way that assumes the path separator is `/`, which works on *nix systems, but not Windows, where the path separator is `\`. I think it's the same sort of problem as the one in [this StackOverflow question](https://stackoverflow.com/questions/2236568/java-noclassdeffounderror-because-of-wrong-slashes).

My hunch is that [this line](https://github.com/RadicalZephyr/boot-junit/blob/b72f094a02882e2d0563341096ebe4a24501fa7d/src/radicalzephyr/boot_junit.clj#L19) is the problem. Might be something worth fixing upstream, if you're interested! :)

**Comment by daveyarwood** [comment]
Closing this PR, as it's Alda v1 specific and Alda v2 will be released soon :crossed_fingers:

**Pull request closed without merging**
